version: '3.8'

services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=filmai_out
    volumes:
      - ./Database:/docker-entrypoint-initdb.d/
    ports:
      - "5435:5432"
  api:
    image: "filmaioutapi"
    environment:
      - ASPNET_ENV=DEVELOPMENT
    ports:
      - "3001:80"
      - "3002:443"
